name: translate_app
description: "Turjam App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  loading_animation_widget: ^1.2.1
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.1
  cool_dropdown: ^2.1.0
  avatar_glow: ^3.0.1
  translator: ^1.0.0
  get: ^4.6.6
  fluttertoast: ^8.2.5
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Arabic
      fonts:
        - asset: assets/fonts/arabicFont.ttf